;;; doom-solarized-osaka-theme.el --- Solarized Osaka for Doom -*- lexical-binding: t; no-byte-compile: t; -*-

;; A Doom Emacs port of craftzdog/solarized-osaka.nvim, including the
;; local overrides from ~/.config/nvim/lua/plugins/colorscheme.lua.

;;; Code:

(require 'doom-themes)

(defgroup doom-solarized-osaka-theme nil
  "Options for the `doom-solarized-osaka' theme."
  :group 'doom-themes)

(defcustom doom-solarized-osaka-padded-modeline doom-themes-padded-modeline
  "If non-nil, add padding to the mode line.
An integer specifies the exact padding in pixels."
  :group 'doom-solarized-osaka-theme
  :type '(choice integer boolean))

(def-doom-theme doom-solarized-osaka
  "A deep, high-contrast Solarized theme inspired by Osaka at night."
  :family 'doom-solarized-osaka
  :background-mode 'dark

  ;; name          default     256         16
  ((bg           '("#001419" "#001419" "black"))
   (fg           '("#9eabac" "#9eabac" "brightwhite"))
   (bg-alt       '("#002c38" "#002c38" "black"))
   (fg-alt       '("#839395" "#839395" "white"))

   ;; Doom expects these to progress from the darkest to the lightest.
   (base0        '("#001419" "#001419" "black"))
   (base1        '("#002c38" "#002c38" "brightblack"))
   (base2        '("#063540" "#063540" "brightblack"))
   (base3        '("#103a3c" "#103a3c" "brightblack"))
   (base4        '("#576d74" "#576d74" "brightblack"))
   (base5        '("#637981" "#637981" "brightblack"))
   (base6        '("#839395" "#839395" "white"))
   (base7        '("#adb7b7" "#adb7b7" "brightwhite"))
   (base8        '("#fdf5e2" "#fdf5e2" "brightwhite"))

   (grey         base4)
   (red          '("#db302d" "#db302d" "red"))
   (orange       '("#c94c16" "#c94c16" "brightred"))
   (green        '("#849900" "#849900" "green"))
   (teal         '("#29a298" "#29a298" "brightgreen"))
   (yellow       '("#b28500" "#b28500" "yellow"))
   (blue         '("#268bd3" "#268bd3" "brightblue"))
   (dark-blue    '("#1a6397" "#1a6397" "blue"))
   (magenta      '("#d23681" "#d23681" "magenta"))
   (violet       '("#6d71c4" "#6d71c4" "brightmagenta"))
   (cyan         '("#29a298" "#29a298" "brightcyan"))
   (dark-cyan    '("#103a3c" "#103a3c" "cyan"))

   ;; Exact shades used by the Neovim theme's UI and diagnostic groups.
   (sidebar-bg   "#002b36")
   (line-nr      "#664c00")
   (red-light    "#ff9a99")
   (orange-dark  "#3c1403")
   (orange-deep  "#5b220a")
   (red-dark     "#380605")
   (red-deep     "#570f0e")
   (cyan-dark    "#103a3c")
   (cyan-deep    "#154e50")
   (green-dark   "#2c3300")
   (magenta-dark "#541131")
   (hint-color   "#fa7334")
   (warning-hi   "#ffbf00")
   (info-hi      "#2aeddd")
   (red-hi       "#f55350")
   (green-hi     "#b7f900")
   (blue-hi      "#46acf5")
   (magenta-hi   "#f254a0")
   (white-hi     "#ffffff")

   ;; Universal syntax classes used by doom-themes.
   (highlight    blue)
   (vertical-bar base2)
   (selection    base2)
   (builtin      orange)
   (comments     base4)
   (doc-comments base4)
   (constants    cyan)
   (functions    blue)
   (keywords     green)
   (methods      blue)
   (operators    green)
   (type         yellow)
   (strings      cyan)
   (variables    fg)
   (numbers      cyan)
   (region       base2)
   (error        red)
   (warning      '("#ffbf00" "#ffbf00" "yellow"))
   (success      green)
   (vc-modified  yellow)
   (vc-added     cyan)
   (vc-deleted   red)

   (-modeline-pad
    (when doom-solarized-osaka-padded-modeline
      (if (integerp doom-solarized-osaka-padded-modeline)
          doom-solarized-osaka-padded-modeline
        4)))
   (modeline-bg          bg-alt)
   (modeline-bg-inactive bg)
   (modeline-fg          base7)
   (modeline-fg-alt      base5))

  (;; Core editor UI
   ((default &override) :background bg :foreground fg)
   (cursor :background base7 :foreground bg-alt)
   (fringe :background bg :foreground base4)
   (hl-line :background bg-alt :extend t)
   (vertical-border :foreground base2)
   (window-divider :foreground base2)
   (window-divider-first-pixel :foreground base2)
   (window-divider-last-pixel :foreground base2)
   (fill-column-indicator :foreground base2)
   ((line-number &override) :foreground line-nr :background bg)
   ((line-number-current-line &override)
    :foreground orange :background bg :weight 'bold)
   ((region &override) :background selection :extend t)
   (secondary-selection :background bg-alt :extend t)
   (minibuffer-prompt :foreground blue :weight 'bold)
   (shadow :foreground base4)
   (link :foreground blue :underline t)
   (link-visited :foreground violet :underline t)
   (highlight :background bg-alt)
   (isearch :foreground base8 :background orange :weight 'bold)
   (isearch-fail :foreground red-light :background red-dark)
   (lazy-highlight :foreground bg :background yellow)
   (match :foreground base8 :background magenta-dark :weight 'bold)
   (show-paren-match
    :foreground red-light :background red :weight 'bold)
   (show-paren-mismatch :foreground bg :background red :weight 'bold)
   (tooltip :foreground fg :background bg)
   (child-frame-border :background base2)
   (internal-border :background bg)

   ;; Syntax. These mirror Solarized Osaka's syntax and Treesitter groups.
   ((font-lock-comment-face &override)
    :foreground comments :slant 'italic)
   ((font-lock-doc-face &override)
    :foreground doc-comments :slant 'italic)
   ((font-lock-keyword-face &override)
    :foreground keywords :slant 'italic)
   ((font-lock-function-name-face &override)
    :foreground functions :slant 'italic)
   ((font-lock-function-call-face &override)
    :foreground functions :slant 'italic)
   ((font-lock-variable-name-face &override) :foreground variables)
   ((font-lock-variable-use-face &override) :foreground variables)
   ((font-lock-property-use-face &override) :foreground cyan)
   ((font-lock-string-face &override) :foreground strings)
   ((font-lock-number-face &override) :foreground numbers)
   ((font-lock-constant-face &override) :foreground constants)
   ((font-lock-type-face &override) :foreground type)
   ((font-lock-builtin-face &override) :foreground builtin)
   ((font-lock-preprocessor-face &override) :foreground red)
   ((font-lock-operator-face &override) :foreground operators)
   ((font-lock-bracket-face &override) :foreground orange)
   ((font-lock-delimiter-face &override) :foreground green)
   ((font-lock-punctuation-face &override) :foreground green)
   ((font-lock-escape-face &override) :foreground "#a13c10")
   ((font-lock-regexp-face &override) :foreground "#2aeddd")
   (regexp-grouping-backslash :foreground orange)
   (regexp-grouping-construct :foreground orange)

   ;; Mode line and workspaces, based on Lualine and Bufferline.
   (mode-line
    :background modeline-bg :foreground modeline-fg
    :box (if -modeline-pad
             `(:line-width ,-modeline-pad :color ,modeline-bg)))
   (mode-line-inactive
    :background modeline-bg-inactive :foreground modeline-fg-alt
    :box (if -modeline-pad
             `(:line-width ,-modeline-pad
               :color ,modeline-bg-inactive)))
   (mode-line-buffer-id :foreground base7 :weight 'bold)
   (doom-modeline-bar :background blue)
   (doom-modeline-bar-inactive :background bg)
   (doom-modeline-buffer-file :foreground base7)
   (doom-modeline-buffer-modified :foreground orange :weight 'bold)
   (doom-modeline-info :foreground info-hi)
   (doom-modeline-warning :foreground warning-hi)
   (doom-modeline-urgent :foreground red)
   (+workspace-tab-face :foreground fg :background bg)
   (+workspace-tab-selected-face
    :foreground bg :background green :weight 'bold)
   (tab-bar :foreground fg :background bg)
   (tab-bar-tab :foreground bg :background green :weight 'bold)
   (tab-bar-tab-inactive :foreground fg :background bg)
   (tab-line :foreground fg :background bg)
   (tab-line-tab-current :foreground bg :background green :weight 'bold)
   (tab-line-tab-inactive :foreground fg :background bg)

   ;; Solaire gives sidebars the same shade as the Neovim configuration.
   (solaire-default-face :foreground fg :background sidebar-bg)
   (solaire-hl-line-face :background base2)
   (solaire-mode-line-face
    :inherit 'mode-line :background modeline-bg)
   (solaire-mode-line-inactive-face
    :inherit 'mode-line-inactive :background modeline-bg-inactive)

   ;; Corfu, Vertico, and Orderless map to nvim-cmp and Telescope.
   (corfu-default :foreground fg :background bg)
   (corfu-current :foreground base8 :background base4)
   (corfu-border :background base2)
   (corfu-bar :background base4)
   (corfu-annotations :foreground comments)
   (corfu-deprecated :foreground comments :strike-through t)
   (corfu-popupinfo :foreground fg :background bg)
   (vertico-current :foreground base8 :background base2 :extend t)
   (completions-common-part :foreground violet :weight 'bold)
   (orderless-match-face-0 :foreground violet :weight 'bold)
   (orderless-match-face-1 :foreground cyan :weight 'bold)
   (orderless-match-face-2 :foreground blue :weight 'bold)
   (orderless-match-face-3 :foreground magenta :weight 'bold)

   ;; Native and LSP diagnostics use the user's brighter overrides.
   ((flycheck-error &override)
    :underline `(:style wave :color ,error))
   ((flycheck-warning &override)
    :underline `(:style wave :color ,warning-hi))
   ((flycheck-info &override)
    :underline `(:style wave :color ,info-hi))
   ((flymake-error &override)
    :underline `(:style wave :color ,error))
   ((flymake-warning &override)
    :underline `(:style wave :color ,warning-hi))
   ((flymake-note &override)
    :underline `(:style wave :color ,info-hi))
   (lsp-face-highlight-textual :background magenta-dark)
   (lsp-face-highlight-read :background magenta-dark)
   (lsp-face-highlight-write :background magenta-dark)
   (lsp-ui-doc-background :foreground fg :background bg)
   (lsp-ui-doc-header :foreground base8 :background bg-alt :weight 'bold)
   (lsp-ui-peek-list :background bg)
   (lsp-ui-peek-peek :background bg)
   (lsp-ui-peek-header :foreground base8 :background bg-alt)
   (lsp-ui-peek-selection :foreground base8 :background base2)
   (lsp-ui-sideline-code-action :foreground hint-color)

   ;; LSP semantic tokens preserve the Neovim semantic palette.
   (lsp-face-semhl-constant :foreground cyan)
   (lsp-face-semhl-variable :foreground fg)
   (lsp-face-semhl-function :foreground blue :slant 'italic)
   (lsp-face-semhl-method :foreground blue :slant 'italic)
   (lsp-face-semhl-namespace :foreground red)
   (lsp-face-semhl-keyword :foreground green :slant 'italic)
   (lsp-face-semhl-string :foreground cyan)
   (lsp-face-semhl-number :foreground cyan)
   (lsp-face-semhl-regexp :foreground info-hi)
   (lsp-face-semhl-operator :foreground green)
   (lsp-face-semhl-type :foreground yellow)
   (lsp-face-semhl-struct :foreground yellow)
   (lsp-face-semhl-class :foreground yellow)
   (lsp-face-semhl-interface :foreground blue)
   (lsp-face-semhl-enum :foreground yellow)
   (lsp-face-semhl-type-parameter :foreground yellow)
   (lsp-face-semhl-member :foreground cyan)
   (lsp-face-semhl-property :foreground blue)
   (lsp-face-semhl-macro :foreground red)
   (lsp-face-semhl-parameter :foreground orange)
   (lsp-face-semhl-label :foreground green)
   (lsp-face-semhl-default-library :foreground orange)

   ;; Diff and Magit use the original dark diagnostic backgrounds.
   ((diff-added &override) :foreground green :background cyan-dark)
   ((diff-changed &override) :foreground yellow :background orange-dark)
   ((diff-removed &override) :foreground red :background red-dark)
   ((diff-refine-added &override)
    :foreground base8 :background cyan-deep :weight 'bold)
   ((diff-refine-changed &override)
    :foreground base8 :background orange-deep :weight 'bold)
   ((diff-refine-removed &override)
    :foreground red-light :background red-deep :weight 'bold)
   (magit-diff-context :foreground base6)
   (magit-diff-context-highlight :foreground fg :background bg-alt)
   (magit-diff-added :foreground green :background cyan-dark)
   (magit-diff-added-highlight
    :foreground green :background cyan-deep :weight 'bold)
   (magit-diff-removed :foreground red :background red-dark)
   (magit-diff-removed-highlight
    :foreground red-light :background red-deep :weight 'bold)
   (magit-diff-hunk-heading :foreground base7 :background base2)
   (magit-diff-hunk-heading-highlight
    :foreground base8 :background dark-blue :weight 'bold)
   (magit-section-heading :foreground blue :weight 'bold)
   (magit-section-heading-selection :foreground orange :weight 'bold)

   ;; Markdown and Org follow the source theme's markup groups.
   (markdown-markup-face :foreground orange)
   (markdown-header-delimiter-face :foreground orange :weight 'bold)
   (markdown-header-face :inherit 'bold :foreground magenta)
   (markdown-header-face-1 :foreground magenta)
   (markdown-header-face-2 :foreground violet)
   (markdown-link-face :foreground blue :underline t)
   (markdown-url-face :foreground blue :underline t)
   (markdown-pre-face :foreground yellow)
   (markdown-code-face :foreground yellow :background green-dark)
   (markdown-inline-code-face
    :foreground yellow :background green-dark)
   ((org-block &override) :background green-dark)
   ((org-block-begin-line &override)
    :foreground comments :background green-dark)
   ((org-block-end-line &override)
    :foreground comments :background green-dark)
   (org-document-title :foreground magenta :weight 'bold)
   (org-level-1 :foreground magenta :weight 'bold)
   (org-level-2 :foreground violet :weight 'bold)
   (org-level-3 :foreground blue :weight 'bold)
   (org-level-4 :foreground cyan :weight 'bold)
   (org-level-5 :foreground yellow :weight 'bold)
   (org-level-6 :foreground orange :weight 'bold)
   (org-link :foreground blue :underline t)
   (org-code :foreground yellow)
   (org-verbatim :foreground cyan)
   (org-todo :foreground violet :weight 'bold)
   (org-done :foreground green :weight 'bold)

   ;; Dashboard, help, Dired, and key discovery.
   (doom-dashboard-banner :foreground blue)
   (doom-dashboard-menu-title :foreground orange :weight 'bold)
   (doom-dashboard-menu-desc :foreground cyan)
   (doom-dashboard-footer :foreground yellow :slant 'italic)
   (doom-dashboard-loaded :foreground comments)
   (which-key-key-face :foreground cyan)
   (which-key-group-description-face :foreground blue)
   (which-key-command-description-face :foreground magenta)
   (which-key-local-map-description-face :foreground violet)
   (which-key-separator-face :foreground comments)
   (dired-directory :foreground blue :weight 'bold)
   (dired-symlink :foreground cyan)
   (dired-ignored :foreground comments)
   (help-key-binding :foreground bg :background cyan)

   ;; Keep terminal colors identical to the generated Ghostty palette.
   (ansi-color-black :foreground bg :background bg)
   (ansi-color-red :foreground red :background red)
   (ansi-color-green :foreground green :background green)
   (ansi-color-yellow :foreground yellow :background yellow)
   (ansi-color-blue :foreground blue :background blue)
   (ansi-color-magenta :foreground magenta :background magenta)
   (ansi-color-cyan :foreground cyan :background cyan)
   (ansi-color-white :foreground base8 :background base8)
   (ansi-color-bright-black :foreground base2 :background base2)
   (ansi-color-bright-red :foreground red-hi :background red-hi)
   (ansi-color-bright-green :foreground green-hi :background green-hi)
   (ansi-color-bright-yellow :foreground warning-hi :background warning-hi)
   (ansi-color-bright-blue :foreground blue-hi :background blue-hi)
   (ansi-color-bright-magenta :foreground magenta-hi :background magenta-hi)
   (ansi-color-bright-cyan :foreground info-hi :background info-hi)
   (ansi-color-bright-white :foreground white-hi :background white-hi)
   (term-color-black :foreground bg :background bg)
   (term-color-red :foreground red :background red)
   (term-color-green :foreground green :background green)
   (term-color-yellow :foreground yellow :background yellow)
   (term-color-blue :foreground blue :background blue)
   (term-color-magenta :foreground magenta :background magenta)
   (term-color-cyan :foreground cyan :background cyan)
   (term-color-white :foreground base8 :background base8)
   (term-color-bright-black :foreground base2 :background base2)
   (term-color-bright-red :foreground red-hi :background red-hi)
   (term-color-bright-green :foreground green-hi :background green-hi)
   (term-color-bright-yellow :foreground warning-hi :background warning-hi)
   (term-color-bright-blue :foreground blue-hi :background blue-hi)
   (term-color-bright-magenta :foreground magenta-hi :background magenta-hi)
   (term-color-bright-cyan :foreground info-hi :background info-hi)
   (term-color-bright-white :foreground white-hi :background white-hi)
   (vterm-color-black :foreground bg :background bg)
   (vterm-color-red :foreground red :background red)
   (vterm-color-green :foreground green :background green)
   (vterm-color-yellow :foreground yellow :background yellow)
   (vterm-color-blue :foreground blue :background blue)
   (vterm-color-magenta :foreground magenta :background magenta)
   (vterm-color-cyan :foreground cyan :background cyan)
   (vterm-color-white :foreground base8 :background base8)
   (vterm-color-bright-black :foreground base2 :background base2)
   (vterm-color-bright-red :foreground red-hi :background red-hi)
   (vterm-color-bright-green :foreground green-hi :background green-hi)
   (vterm-color-bright-yellow :foreground warning-hi :background warning-hi)
   (vterm-color-bright-blue :foreground blue-hi :background blue-hi)
   (vterm-color-bright-magenta
    :foreground magenta-hi :background magenta-hi)
   (vterm-color-bright-cyan :foreground info-hi :background info-hi)
   (vterm-color-bright-white :foreground white-hi :background white-hi)))

;;; doom-solarized-osaka-theme.el ends here
