[ui]
styleset-name=solarized-osaka
sidebar-width=0
threading-enabled=true
show-thread-context=true

index-columns=flags>4,date<8,name<18,subject<*
column-date={{.DateAutoFormat .Date.Local}}
column-name={{index (.From | names) 0}}
column-flags={{.Flags | join ""}}
column-subject={{.ThreadPrefix}}{{if .Subject}}{{.Subject}}{{else}}(no subject){{end}}

[viewer]
pager=less -R
header-layout=From|To,Cc|Bcc,Date,Subject

[filters]
text/plain=colorize
text/x-diff=hldiff
text/x-patch=hldiff
text/calendar=calendar
text/html=html | colorize
text/*=bat -fP --file-name="$AERC_FILENAME"
message/delivery-status=colorize
message/rfc822=colorize

[compose]
header-layout=To|From,Subject

[general]
unsafe-accounts-conf=false
